[theme]
base = "light"
primaryColor = "#9fe870"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#e8ebe6"
textColor = "#0e0f0c"
font = "sans serif"

[server]
headless = true
port = 8501

[client]
toolbarMode = "minimal"


